POST http://localhost:3000/api/v1/user  HTTP/1.1
content-type: application/json

  {
    "username": "filip",
    "first_name": "pino",
    "last_name": "erresd",
    "membership": "YP1",
    "email": "jo55ad@gmail.com",
    "subscriber": false,
    "telephone": 23223222,
    "address": "vic",
    "city": "barcelona",
    "how_meet_us": null,
    "dni": "T1232404T",
    "birth_date": "1980-12-25",
    "role": "admin",
    "password": "1453123"
  }