POST http://localhost:3000/api/v1/user  HTTP/1.1
content-type: application/json

  {
    "username": "john",
    "first_name": "jim",
    "last_name": "asdasd",
    "membership": "YP1",
    "email": "jofdad@gmail.com",
    "subscriber": false,
    "telephone": 222223222,
    "address": "vic",
    "city": "barcelona",
    "how_meet_us": null,
    "dni": "T1234405T",
    "birth_date": "1980-12-25",
    "role": "admin",
    "password": "123123"
  }