name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i'
          TARGET: ${{ secrets.WORKING_DIR }}
          SOURCE: '.'
          SCRIPT_BEFORE: |
            sudo whoami
            sudo ls -al
          SCRIPT_AFTER: |
            sudo cd ${{ secrets.WORKING_DIR }}
            sudo git pull origin main
            sudo npm install
            sudo npm run build
            sudo pm2 restart umbracle
            sudo cd /home/ubuntu/
            sudo touch deployed.txt
            sudo echo "Deployed at $(date)" > deployed.txt
