name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i'
          TARGET: ${{ secrets.WORKING_DIR }}
          SOURCE: 'dist/'
          EXCLUDE: '/dist/, /node_modules/'
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            cd ${{ secrets.WORKING_DIR }}
            git pull origin main
            npm install
            npm run build
            pm2 restart umbracle
            cd /home/ubuntu/
            sudo touch deployed.txt
            sudo echo "Deployed at $(date)" > deployed.txt
